### ISSUE TITLE
Added : Schema.org Type "Breadcrumb" image url.

### ISSUE THREAD

**Issue by miiitaka** [miiitaka/wp-structuring-markup#127]
image property required.
feature image of Post set.
https://developers.google.com/search/docs/data-types/breadcrumbs

**Comment by inetbiz** [comment]
image is not required on a breadcrumb list. Most WP sites use Yoast SEO which includes breadcrumb schema.

**Comment by miiitaka** [comment]
Closed because the property is gone.
