### ISSUE TITLE
PageNavigation set up a different menu ID.

### ISSUE THREAD

**Issue by miiitaka** [miiitaka/wp-structuring-markup#183]
WordPress.org Support Threads
https://wordpress.org/support/topic/wpml-compatibility-90/

**Comment by miiitaka** [comment]
We modified it so that data is automatically acquired, so it is done.

**Comment by davideprevosto** [comment]
Hello @miiitaka, the trick works on categories contained in menu, but not (for example) on **custom** taxonomies
