### ISSUE TITLE
Tesimonial?

### ISSUE THREAD

**Issue by good3n** [miiitaka/wp-structuring-markup#214]
Any plans to add testimonial schema?

**Comment by miiitaka** [comment]
Hi @good3n,

Do you mean reviews? https://schema.org/Review

**Comment by good3n** [comment]
Yes sorry, reviews.

**Comment by miiitaka** [comment]
@good3n 
Yes, issue is registered.
https://github.com/miiitaka/wp-structuring-markup/issues/102

We have not implemented it yet, but we plan to release it in the near future.
Please wait till then. Thank you.
