### ISSUE TITLE
Schema Type: Article -- bug: 1st image in content is always used if check is on, even if no image present

### ISSUE THREAD

**Issue by waviaei** [miiitaka/wp-structuring-markup#398]
For Schema Type > Article > image.

The setting gives me impression that logic here supposed to be that:

1. Use thumbnail, if any are set; else, if not
2. Use the 1st image in content if the "Set the first image in the content." checkbox is checked; else, if not
3. Use default image, if any are set; else
4. do not output @type ImageObject.

But currently it does not behave like that. If "Set the first image in the content." checkbox is checked, it will always use logic 2, even if there are no images used in the content.

Fix the part for logic 2, so that it does not only check for `( isset( $options['content_image'] ) &&  $options['content_image'] === 'on' )`, but also check for existance of `$images` too.

**Comment by miiitaka** [comment]
That's true. to correct.

**Comment by miiitaka** [comment]
Released in version 4.7.0.
